export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUOT_REQUEST: "LOGOUOT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUOT_FAIL: "LOGOUOT_FAIL",
};

export const userConstant = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  USER_REGISTTER_SUCCESS: "USER_REGISTTER_SUCCESS",
};

export const registerConstant = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTTER_SUCCESS: "REGISTTER_SUCCESS",
  GET_REGISTER_REQUEST: "GET_REGISTER_REQUEST",
  GET_REGISTER_FAIL: "GET_REGISTER_FAIL",
  GET_REGISTTER_SUCCESS: "GET_REGISTTER_SUCCESS",
};

export const profileConstant = {
  PROFILE_REQUEST: "PROFILE_REQUEST",
  PROFILE_FAIL: "PROFILE_FAIL",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  REMOVE_PROFILE_REQUEST: "REMOVE_PROFILE_REQUEST",
  REMOVE_PROFILE_FAIL: "REMOVE_PROFILE_FAIL",
  REMOVE_PROFILE_SUCCESS: "REMOVE_PROFILE_SUCCESS",

  EDIT_PROFILE_REQUEST: "EDIT_PROFILE_REQUEST",
  EDIT_PROFILE_FAIL: "EDIT_PROFILE_FAIL",
  EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_FAIL: "UPDATE_PROFILE_FAIL",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
};
